// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ggC7CGPMRraha4Go3t--sCc9prb2mts',
    appId: '1:519871489490:web:b30dccb2ff83c8fa6d140b',
    messagingSenderId: '519871489490',
    projectId: 'mobilabshoppinglist',
    authDomain: 'mobilabshoppinglist.firebaseapp.com',
    storageBucket: 'mobilabshoppinglist.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI8f-mlqftxrJtpWLIh4E2BX5fMmVVHIY',
    appId: '1:519871489490:android:45a5679f5eff18ce6d140b',
    messagingSenderId: '519871489490',
    projectId: 'mobilabshoppinglist',
    storageBucket: 'mobilabshoppinglist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7rr6OetDN2Gt27YXRWZn8fhCmSBAkLtg',
    appId: '1:519871489490:ios:cada634789f18c5f6d140b',
    messagingSenderId: '519871489490',
    projectId: 'mobilabshoppinglist',
    storageBucket: 'mobilabshoppinglist.appspot.com',
    iosClientId:
        '519871489490-j9mahihncdu3bksijndm1q0g5vglgjgm.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.mobi-lab-shopping-list-app',
  );
}
